// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuEJ5vku9B-EFjiYK13wJE6A2NKngQ6tw',
    appId: '1:486456195304:web:752d3c6f1c8738e833715d',
    messagingSenderId: '486456195304',
    projectId: 'cyclecare-201ef',
    authDomain: 'cyclecare-201ef.firebaseapp.com',
    storageBucket: 'cyclecare-201ef.appspot.com',
    measurementId: 'G-XN5DMZ9ZYK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpzxP0FLRPUm8jp9F8D8izuHz2gqBxQyc',
    appId: '1:486456195304:android:c9bcf2f0e904000833715d',
    messagingSenderId: '486456195304',
    projectId: 'cyclecare-201ef',
    storageBucket: 'cyclecare-201ef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-Aiyo87VjceBYAAy-jv6-azhKUpPPmys',
    appId: '1:486456195304:ios:8098eb3f90232d1733715d',
    messagingSenderId: '486456195304',
    projectId: 'cyclecare-201ef',
    storageBucket: 'cyclecare-201ef.appspot.com',
    androidClientId:
        '486456195304-aqiqi1t6l8k1tkqffhc47jku9tgheu03.apps.googleusercontent.com',
    iosClientId:
        '486456195304-ufecdieutjb958lhscn70vdejskqur0e.apps.googleusercontent.com',
    iosBundleId: 'com.example.cyclecare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-Aiyo87VjceBYAAy-jv6-azhKUpPPmys',
    appId: '1:486456195304:ios:2a97d53f8a96178633715d',
    messagingSenderId: '486456195304',
    projectId: 'cyclecare-201ef',
    storageBucket: 'cyclecare-201ef.appspot.com',
    androidClientId:
        '486456195304-aqiqi1t6l8k1tkqffhc47jku9tgheu03.apps.googleusercontent.com',
    iosClientId:
        '486456195304-1jm24u3dcjduc1cqh53vemfgmq1iqqvg.apps.googleusercontent.com',
    iosBundleId: 'com.example.cyclecare.RunnerTests',
  );
}
